[package]
name = "rowser-layout"
description = "Rrowser layout: taffy box layout with cosmic-text shaping."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
log = "0.4"
cosmic-text = "0.17.0"
rowser-dom = { path = "../dom" }
rowser-parsing = { path = "../parsing" }
taffy = "0.14.0"
